export const zIndices = {
	"z-optionsModal": "9",
	"z-logo": "10",
	"z-message": "10",
	"z-overlay": "10",
	"z-tooltip": "10",
	"z-header": "10",
	"z-gSide": "10",
	"z-sidebar": "10",
	"z-modal": "20",
	"z-snackbar": "30",
	"z-search": "2",
	"z-lessonContainer": "2",
	"z-positive": "1",
	"z-negative": "-1",
	"z-negativePlus": "-2",
	"z-backgroundCircles": "-10",
	"z-buttonVideo": "8",
	"z-warning": "9",
};
